### ISSUE TITLE
Unhandled error results in error message: No handlers could be found for logger "tornado.web"

### ISSUE THREAD

**Issue by ssadler** [enaeseth/swirl#3]
I'm not sure if this belongs in the Tornado issue tracker, but I encountered it in Swirl and it can also be "fixed" in Swirl.

To reproduce, call this handler:

```
class SwirlHandler(tornado.web.RequestHandler):
    @swirl.asynchronous
    def get(self):
        raise Exception()
```

Can be "fixed" by adding this line to Swirl:

```
logging.getLogger("tornado.web").addHandler(logging.StreamHandler())
```

But this looks like a hack to me. I'm not sure what the interaction is here because Tornado doesn't define a "tornado.web" logger, as far as I can see.

**Comment by ssadler** [comment]
Also reported this issue to Tornado: http://github.com/facebook/tornado/issues/issue/84

**Comment by enaeseth** [comment]
Looks like the Tornado people fixed this.
